### ISSUE TITLE
Sync-direction is not shown when filename is very long

### ISSUE THREAD

**Issue by cziehr** [splitbrain/dokuwiki-plugin-sync#33]
If the filename is very long, then the radio-buttons which are necessary to set the direction are not shown. Top of the site:

![sync-bug_1](https://cloud.githubusercontent.com/assets/580647/6399672/4700cec4-bdf4-11e4-9120-b3cf5a5b7619.png)

Item with a very long filename:

![sync-bug_2](https://cloud.githubusercontent.com/assets/580647/6399673/470aad2c-bdf4-11e4-9c24-9e8c069b279c.png)

I already examined the sourcecode, but the sync-plugin doesn't assign an own css-class to the table which could be used to limit the width of the table-cell for the sync-plugin.

**Comment by stvoigt** [comment]
Ich kehre zur�ck am 08.08.2016.

Ich werde Ihre Nachricht nach meiner R�ckkehr beantworten. Herzlichen Dank
f�r ihr Verst�ndnis.

I will answer your message after returning.


Hinweis: Dies ist eine automatische Antwort auf Ihre Nachricht  "Re:
[splitbrain/dokuwiki-plugin-sync] Sync-direction is not shown when filename
is very long (#33)" gesendet am 01.08.2016 09:43:10.

Diese ist die einzige Benachrichtigung, die Sie empfangen werden, w�hrend
diese Person abwesend ist.
