### ISSUE TITLE
Problem with Sync xmlrpc and Dreamhost

### ISSUE THREAD

**Issue by nminetti** [splitbrain/dokuwiki-plugin-sync#43]
Hi,

I'm trying to use the plugin to synchronize the dokuwiki in my laptop with one I want to have as backup hosted in dreamhost.

I have some issues that reported to Dreamhost support and this is their answer (no clue how to do what they ask me to do)

"The temporary bans came because of numerous accesses to the xmlrpc.php
script over a very small amount of time. I recommend slowing down the
import process. The logs show that the xmlrpc.php file was accessed eight
times in the span of 21 seconds just before the first set of errors and
then eight times in 23 seconds before the second set.

If you've slowed down the process and you're still running into issues,
let us know and we'll discuss whitelisting possibilities."

Please help!

**Comment by splitbrain** [comment]
Sorry, but slowing down the process makes no sense to me and would be complicated. Maybe get a different hoster or upgrade to a better package?
